"""Trend detection and anomaly alerting for eval metrics.

Goes beyond simple threshold alerts:
- Sliding window trend detection (pass_rate declining over N runs)
- Z-score anomaly detection for metric outliers
- Rate-of-change alerts
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field

from agentlens.core.models import AlertSeverity


@dataclass
class TrendAlert:
    """An alert generated by trend or anomaly detection."""
    alert_type: str  # declining_trend, anomaly, rate_change
    metric_key: str
    severity: AlertSeverity
    message: str
    details: dict[str, object] = field(default_factory=dict)


@dataclass
class TrendAnalysis:
    """Results of trend analysis on a metric series."""
    metric_key: str
    values: list[float]
    trend_direction: str  # rising, falling, stable
    slope: float
    alerts: list[TrendAlert] = field(default_factory=list)


def _mean(values: list[float]) -> float:
    return sum(values) / len(values) if values else 0.0


def _stddev(values: list[float]) -> float:
    if len(values) < 2:
        return 0.0
    m = _mean(values)
    variance = sum((v - m) ** 2 for v in values) / (len(values) - 1)
    return math.sqrt(variance)


def _simple_slope(values: list[float]) -> float:
    """Compute simple linear regression slope."""
    n = len(values)
    if n < 2:
        return 0.0
    x_mean = (n - 1) / 2
    y_mean = _mean(values)
    numerator = sum((i - x_mean) * (v - y_mean) for i, v in enumerate(values))
    denominator = sum((i - x_mean) ** 2 for i in range(n))
    if denominator == 0:
        return 0.0
    return numerator / denominator


def detect_declining_trend(
    values: list[float],
    *,
    metric_key: str = "pass_rate",
    window_size: int = 5,
    decline_threshold: float = -2.0,
) -> TrendAlert | None:
    """Detect a declining trend over a sliding window.

    Args:
        values: Time-ordered metric values (oldest first).
        window_size: Number of recent values to analyze.
        decline_threshold: Slope below which triggers alert.
    """
    if len(values) < window_size:
        return None

    window = values[-window_size:]
    slope = _simple_slope(window)

    if slope < decline_threshold:
        return TrendAlert(
            alert_type="declining_trend",
            metric_key=metric_key,
            severity=AlertSeverity.WARNING,
            message=(
                f"{metric_key} showing declining trend: "
                f"slope={slope:.2f} over last {window_size} runs"
            ),
            details={
                "slope": round(slope, 3),
                "window_size": window_size,
                "window_values": window,
            },
        )
    return None


def detect_anomaly(
    values: list[float],
    *,
    metric_key: str = "pass_rate",
    z_threshold: float = 2.0,
) -> TrendAlert | None:
    """Detect anomalous values using Z-score.

    Args:
        values: Time-ordered metric values. The last value is tested.
        z_threshold: Z-score above which triggers alert.
    """
    if len(values) < 3:
        return None

    historical = values[:-1]
    current = values[-1]

    mean = _mean(historical)
    std = _stddev(historical)

    if std == 0:
        return None

    z_score = abs(current - mean) / std
    if z_score >= z_threshold:
        direction = "above" if current > mean else "below"
        return TrendAlert(
            alert_type="anomaly",
            metric_key=metric_key,
            severity=AlertSeverity.WARNING if z_score < 3.0 else AlertSeverity.CRITICAL,
            message=(
                f"{metric_key} anomaly: current={current:.1f} is {z_score:.1f}σ "
                f"{direction} mean={mean:.1f}"
            ),
            details={
                "z_score": round(z_score, 2),
                "current": current,
                "mean": round(mean, 2),
                "stddev": round(std, 2),
            },
        )
    return None


def detect_rate_change(
    values: list[float],
    *,
    metric_key: str = "pass_rate",
    drop_threshold: float = 10.0,
) -> TrendAlert | None:
    """Detect sudden drops between consecutive values.

    Args:
        values: Time-ordered metric values.
        drop_threshold: Absolute drop that triggers alert.
    """
    if len(values) < 2:
        return None

    drop = values[-2] - values[-1]
    if drop >= drop_threshold:
        return TrendAlert(
            alert_type="rate_change",
            metric_key=metric_key,
            severity=AlertSeverity.WARNING if drop < 20 else AlertSeverity.CRITICAL,
            message=(
                f"{metric_key} dropped by {drop:.1f} "
                f"({values[-2]:.1f} -> {values[-1]:.1f})"
            ),
            details={
                "previous": values[-2],
                "current": values[-1],
                "drop": round(drop, 2),
            },
        )
    return None


def analyze_metric_trend(
    values: list[float],
    *,
    metric_key: str = "pass_rate",
    window_size: int = 5,
    decline_threshold: float = -2.0,
    z_threshold: float = 2.0,
    drop_threshold: float = 10.0,
) -> TrendAnalysis:
    """Run all trend detection analyses on a metric series."""
    slope = _simple_slope(values[-window_size:]) if len(values) >= 2 else 0.0

    if slope > 0.5:
        direction = "rising"
    elif slope < -0.5:
        direction = "falling"
    else:
        direction = "stable"

    alerts: list[TrendAlert] = []

    trend = detect_declining_trend(
        values, metric_key=metric_key,
        window_size=window_size, decline_threshold=decline_threshold,
    )
    if trend:
        alerts.append(trend)

    anomaly = detect_anomaly(
        values, metric_key=metric_key, z_threshold=z_threshold,
    )
    if anomaly:
        alerts.append(anomaly)

    rate = detect_rate_change(
        values, metric_key=metric_key, drop_threshold=drop_threshold,
    )
    if rate:
        alerts.append(rate)

    return TrendAnalysis(
        metric_key=metric_key,
        values=values,
        trend_direction=direction,
        slope=round(slope, 3),
        alerts=alerts,
    )
